##
# title: Constants.py
# by: Brian Kim
# description: constants needed for the 4 tank syste
#

DEFAULT_LARGE_TANK_RADIUS = 3.192
DEFAULT_LARGE_TANK_RADIUS = 3.192
DEFAULT_LARGE_TANK_HEIGHT = 5.0
DEFAULT_SMALL_TANK_RADIUS = 2.985
DEFAULT_SMALL_TANK_HEIGHT = 5.0
DEFAULT_DRAIN_RADIUS = 1.00
DEFAULT_DRAIN_HEIGHT=  0.50
DEFAULT_PUMP_RADIUS = 0.838
DEFAULT_PUMP_VELOCITY = 2.5
DEFAULT_PUMP_RATIO = 0.333

DEFAULT_K1 = 5.51 
DEFAULT_K2 = 6.58
